### ISSUE TITLE
Missing Assembly Examples

### ISSUE THREAD

**Issue by amedina64** [jminjares4/MSP432-Example-Codes#5]
This repo could use some assembly examples that explain whats happening in a concise manner for the different peripherals. Usually, the lectures cover assembly and C, however, there are few resources on assembly.

**Comment by jminjares4** [comment]
Thanks for your feedback. While I appreciate your suggestion for assembly examples, our repository is primarily focused on providing C code examples for the MSP432.

However, if you're interested in viewing assembly code, you can utilize the "Disassembly" feature in Code Composer Studio (CCS) to explore the generated assembly code from our C examples. Here's how you can use it:

1. Open my project in Code Composer Studio.
2. Navigate to the "View" menu at the top of the CCS window.
3. Select "Disassembly" from the dropdown menu.
4. A new tab or window will open, displaying the assembly code corresponding to my C code.

It's important to note that the objective of my repository is to provide a brief introduction to using the MSP432 in C, rather than focusing on assembly language. Additionally, my repository is not intended to be used for solutions in a class-oriented context.

I hope this clarifies things for you. If you have any further questions or need assistance, please feel free to ask.
